language: node_js

node_js: stable

sudo: required

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
  - sudo apt-get -qq install g++-4.8
  - curl https://install.meteor.com | /bin/sh
  - export PATH="$HOME/.meteor:$PATH"
  - npm install -g spacejam
  - meteor npm install

env:
  - CXX=g++-4.8



script:
  - "npm run test"
