language: node_js

sudo: required

node_js: "4.4.7"

before_install:
  - "curl https://install.meteor.com | /bin/sh"
  - export PATH="$HOME/.meteor:$PATH"
  - "npm install -g spacejam"
  - "meteor npm install"

script:
  - "npm run test"
